"""Intelligence Data Models."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
import uuid

def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")

def _new_id() -> str:
    return uuid.uuid4().hex[:8]

@dataclass
class Observation:
    """A structured proactive insight generated by the engine."""
    id: str = field(default_factory=_new_id)
    type: str = "general" # e.g. overdue_task, stale_workspace, learning_candidate
    priority: str = "LOW" # LOW, MEDIUM, HIGH, CRITICAL
    confidence: float = 1.0
    reason: str = ""
    suggested_action: str = ""
    
    workspace_id: str | None = None
    related_entities: list[str] = field(default_factory=list)
    generated_from: list[str] = field(default_factory=list) # e.g. ["workspace.tasks"]
    
    learning_candidate: bool = False
    
    created_at: str = field(default_factory=_now)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": self.type,
            "priority": self.priority,
            "confidence": self.confidence,
            "reason": self.reason,
            "suggested_action": self.suggested_action,
            "workspace_id": self.workspace_id,
            "related_entities": self.related_entities,
            "generated_from": self.generated_from,
            "learning_candidate": self.learning_candidate,
            "created_at": self.created_at,
        }
        
    @classmethod
    def from_dict(cls, data: dict) -> Observation:
        return cls(
            id=data.get("id", _new_id()),
            type=data.get("type", "general"),
            priority=data.get("priority", "LOW"),
            confidence=data.get("confidence", 1.0),
            reason=data.get("reason", ""),
            suggested_action=data.get("suggested_action", ""),
            workspace_id=data.get("workspace_id"),
            related_entities=data.get("related_entities", []),
            generated_from=data.get("generated_from", []),
            learning_candidate=data.get("learning_candidate", False),
            created_at=data.get("created_at", _now()),
        )
